# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-21 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
