# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-21 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_auto_20171120_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.AddField(
            model_name='trip',
            name='users',
            field=models.ManyToManyField(related_name='trips', to='exam_app.User'),
        ),
    ]
