# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.TextField(max_length=100)),
                ('description', models.TextField()),
                ('on', models.DateField(null=True)),
                ('to', models.DateField(null=True)),
                ('user', models.ManyToManyField(related_name='travels', to='users.User')),
            ],
        ),
    ]
